### ISSUE TITLE
Is it available in maven repository?

### ISSUE THREAD

**Issue by RussiaVk** [simdjson/simdjson-java#12]

**Comment by piotrrzysko** [comment]
Not yet. I'd like to first finish work on basic functionalities, e.g. float parsing, and perhaps support for Unicode characters. Would you like to use the library in your project?

**Comment by RussiaVk** [comment]
> Not yet. I'd like to first finish work on basic functionalities, e.g. float parsing, and perhaps support for Unicode characters. Would you like to use the library in your project?

Thanks for your work. I plan to use this library in the future

**Comment by piotrrzysko** [comment]
Cool, I'll let you know in this issue when it's available in Maven.

**Comment by ToutatisGc** [comment]
Please let me know, I'm looking forward to using this library in java too :)

**Comment by JohannesLichtenberger** [comment]
Me too :)

**Comment by ryust** [comment]
Me three...

**Comment by piotrrzysko** [comment]
The first version is now available in maven central: https://central.sonatype.com/artifact/org.simdjson/simdjson-java/0.1.0. Please take a look at the README or Issues to see what this version is missing. Any feedback would be greatly appreciated
