### ISSUE TITLE
Stream reader?

### ISSUE THREAD

**Issue by ryust** [simdjson/simdjson-java#19]
Is there no support for an I/O stream reader (vs byte array) parser like all the other JSON libraries have? Seems odd for a high speed parser to load large JSON structures into a byte[] with its subsequent memory consumption. I'd like to use this library in an Android app.

**Comment by piotrrzysko** [comment]
Currently, there is no such support. However, it's definitely worth considering to add this feature in the future.

**Comment by piotrrzysko** [comment]
I'm closing this one. Let's use #33 to track any progress in adding support for streaming parsing.
