### ISSUE TITLE
Error String Parsing

### ISSUE THREAD

**Issue by zekronium** [simdjson/simdjson-java#26]
There is a possibility there might be a bug with parsing strings. I am not sure if the original SIMDJSON behaves the same, but these are some errors I saw in some benchmarks I tried to perform.

```
[ERROR] Errors: 
[ERROR] org.benchmark.json.decode.DecodeTest.test_smid_json_map[deep_bench]
[ERROR]   Run 1: DecodeTest.test_smid_json_map:298 » JsonParsing Unclosed string. A string is opened, but never closed.
[INFO] 
[ERROR] org.benchmark.json.decode.DecodeTest.test_smid_json_map[wide_bench]
[ERROR]   Run 1: DecodeTest.test_smid_json_map:298 » JsonParsing Unescaped characters. Within strings, there are characters that should be escaped.
[INFO] 
[ERROR] org.benchmark.json.decode.DecodeTest.test_smid_validity[deep_bench]
[ERROR]   Run 1: DecodeTest.test_smid_validity:306 » JsonParsing Unclosed string. A string is opened, but never closed.
[INFO] 
[ERROR] org.benchmark.json.decode.DecodeTest.test_smid_validity[wide_bench]
[ERROR]   Run 1: DecodeTest.test_smid_validity:306 » JsonParsing Unescaped characters. Within strings, there are characters that should be escaped.
that should be escaped.
```

For now I can not debug this, since for the current moment I do not have access to compatible hardware so I am testing in a codespace VM.

Other json libraries such as: Jackson, JacksonAfterburner, JacksonBlackbird,JacksonDatabind,FastJSON2,Jsoniter,DSLJson cope with this correctly.

These JSON's are taken from Vert.x benchmarks https://github.com/eclipse-vertx/vert.x/tree/master/src/test/resources

**Comment by piotrrzysko** [comment]
Thanks for reporting this. Did you test version 0.1.0 or a snapshot with recent changes?

**Comment by zekronium** [comment]
> Thanks for reporting this. Did you test version 0.1.0 or a snapshot with recent changes?
Its most recent snapshot of commit `6772c988acfaaece53e0139e66fb15d94f641ae7`

**Comment by piotrrzysko** [comment]
I just merged a patch that should fix this bug. Feel free to reopen the issue if you still see this problem.
