### ISSUE TITLE
request:compatibility for java17

### ISSUE THREAD

**Issue by RussiaVk** [simdjson/simdjson-java#28]
Is it possible to update the target Java version of the project to Java 17 in the next Maven release, considering that Java 17 can run SIMD API without any issues?

**Comment by piotrrzysko** [comment]
I don't think it's possible because the library relies on certain functionalities that are not available in Java 17, such as [Math.unsignedMultiplyHigh](https://github.com/simdjson/simdjson-java/blob/a7a429d8fe8603b8a941cf336ca1f9e02e5c2aff/src/main/java/org/simdjson/NumberParser.java#L164).

**Comment by RussiaVk** [comment]
> [Math.unsignedMultiplyHigh](https://github.com/simdjson/simdjson-java/blob/a7a429d8fe8603b8a941cf336ca1f9e02e5c2aff/src/main/java/org/simdjson/NumberParser.java#L164).

It can be solved using "[JEP238](https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html)".
We can copy source of unsignedMultiplyHigh method Into NumberParser:
![image](https://github.com/simdjson/simdjson-java/assets/43515485/8fad4d0d-1efe-41a4-8659-08e1eaee4def)

**Comment by piotrrzysko** [comment]
Yes, but this function is annotated with @IntrinsicCandidate, which means that if we copy it, we will lose support from the JVM in terms of optimization.

**Comment by RussiaVk** [comment]
> Yes, but this function is annotated with @IntrinsicCandidate, which means that if we copy it, we will lose support from the JVM in terms of optimization.

What I mean is, in order to comply with the “Multi Release” feature, we should create a separate duplicate file for the NumberParser class (as well as the source code for unsignedMultiplyHigh) for Java 17. It will not conflict with Java 20.

**Comment by piotrrzysko** [comment]
OK, I get it. Have you tried applying the changes you mentioned and testing the library's performance on Java 17? I'm asking because it would be good to know if there is any advantage over other JSON parsers in terms of performance and, thereby, if there is a reason to add support for Java 17. The library highly relies on the advancements in the Vector API, so the newer the Java version, the better the performance we should expect.

**Comment by RussiaVk** [comment]
> OK, I get it. Have you tried applying the changes you mentioned and testing the library's performance on Java 17? I'm asking because it would be good to know if there is any advantage over other JSON parsers in terms of performance and, thereby, if there is a reason to add support for Java 17. The library highly relies on the advancements in the Vector API, so the newer the Java version, the better the performance we should expect.

Not yet. I'm a gradle noob, so I'm currently using maven, and I don't know how to run the code in the src/jhm/java directory through maven.
