### ISSUE TITLE
How to use the idea

### ISSUE THREAD

**Issue by lixiaoyong12** [simdjson/simdjson-java#46]
How to use the idea
![image](https://github.com/simdjson/simdjson-java/assets/34184204/dcb60bb8-86ea-4abe-b76e-493cc866377b)

**Comment by piotrrzysko** [comment]
Perhaps you are missing the `--add-modules=jdk.incubator.vector` argument. It should look something like this: `java --add-modules jdk.incubator.vector Main`

**Comment by lixiaoyong12** [comment]
> --add-modules=jdk.incubator.vector

![image](https://github.com/simdjson/simdjson-java/assets/34184204/cd0bac49-8c0d-4005-9ac8-c62a57e07a97)

**Comment by piotrrzysko** [comment]
Do I understand correctly that you are passing `--add-modules=jdk.incubator.vector` as a compiler argument? In my previous comment, I provided an example where I'm passing it as a JVM argument. Are you also doing that?

**Comment by lixiaoyong12** [comment]
![image](https://github.com/simdjson/simdjson-java/assets/34184204/accea702-32c1-4072-b18a-8653d16c94e8)

**Comment by piotrrzysko** [comment]
What would you like to use to generate these JAR files? simdjson-java is available in the Maven Central repository, and as its documentation states, it supports all Java versions from 18 onward.

**Comment by piotrrzysko** [comment]
I'm closing this because, without additional information (mentioned in the above comment), I cannot address it. Feel free to reopen if you can answer my question.
