### ISSUE TITLE
simdjson is much slower than jackson

### ISSUE THREAD

**Issue by z00407087** [simdjson/simdjson-java#48]
I make a peformance test between simdjson and jackson, the result is simdjson slower much than jackson. why?
the result:
SimdJson deserialize run 100000 cost 80532ms;
Jackson deserialize run 100000 cost 1902ms;
code demo:
![image](https://github.com/simdjson/simdjson-java/assets/57161512/bd736f51-b307-4e82-8cd8-2300d3d6cfce)
profiler:

**Comment by z00407087** [comment]
add profile:
![Uploading simdjson-profiler.png…]()

**Comment by piotrrzysko** [comment]
Based on the screen you shared, I assume that you didn't perform any warm-up iterations, which are crucial to allow JIT to kick in. Have you followed any guidelines regarding (micro)benchmarking (e.g., described here: https://www.oracle.com/technical-resources/articles/java/architect-benchmarking.html)?

Also, it would be good to see on what data you ran the benchmark. Would you mind sharing it?

**Comment by piotrrzysko** [comment]
I'm closing this because, without additional information (mentioned in the above comment), I cannot address it. Feel free to reopen if you can answer my questions.
